import type { Destination } from '@/types';
import type { AIDestinationSearchParams, AIDestinationSearchResponse } from './openrouter';
import {
  filterAndRankCuratedDestinations,
  generateSearchSummary,
  generateFollowUps,
} from './openrouter';

// Real Unsplash travel photography pool
const UNSPLASH_IMAGES = {
  coastal: [
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1510414842594-a61782153f5b?q=80&w=1000&auto=format&fit=crop',
  ],
  mountain: [
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1546708973-b339540b5162?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=1000&auto=format&fit=crop',
  ],
  historic: [
    'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1599661046289-e31897846e41?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1568454537842-d933259bb258?q=80&w=1000&auto=format&fit=crop',
  ],
  nature: [
    'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1000&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1000&auto=format&fit=crop',
  ],
};

function formatTitleCase(str: string): string {
  return str
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Curated destinations for France / Paris
 */
const FRANCE_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_paris',
    name: 'Paris & Montmartre',
    country: 'France',
    continent: 'Europe',
    tagline: 'Art, historic bistros & iconic Eiffel panoramas',
    description: 'The City of Light captivates with world-class museums, romantic Seine riverside walks, and charming cobblestone alleys.',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to October',
    averageTemp: '20°C',
    idealDays: 5,
    vibes: ['Historic Old Towns', 'Romantic', 'Café Culture', 'Architecture'],
    highlights: ['Eiffel Tower at Twilight', 'Louvre Museum Masterpieces', 'Montmartre & Sacré-Cœur'],
    foodTypes: ['Fresh Butter Croissants', 'Duck Confit', 'French Macarons', 'Artisanal Wine & Cheese'],
    matchScore: 98,
    matchReason: 'Unmatched romantic cafe culture, historic architecture, and world-class fine dining.',
  },
  {
    id: 'dest_custom_french_riviera',
    name: 'French Riviera (Nice & Cannes)',
    country: 'France',
    continent: 'Europe',
    tagline: 'Azure Mediterranean glamour & palm-lined promenades',
    description: 'Sun-drenched seaside towns, vibrant flower markets, and glamorous coastal vistas along the Côte d’Azur.',
    coverImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to September',
    averageTemp: '26°C',
    idealDays: 4,
    vibes: ['Chill & Coastal', 'Luxury Escapes', 'Scenic Views'],
    highlights: ['Promenade des Anglais', 'Old Town Nice Flower Market', 'Eze Medieval Clifftop Village'],
    foodTypes: ['Salade Niçoise', 'Fresh Seafood Bouillabaisse', 'Socca Chickpea Crêpes'],
    matchScore: 97,
    matchReason: 'Classic Mediterranean luxury paired with pristine azure coastal vistas.',
  },
  {
    id: 'dest_custom_provence',
    name: 'Provence & Luberon Valleys',
    country: 'France',
    continent: 'Europe',
    tagline: 'Purple lavender fields, stone hamlets & olive groves',
    description: 'A peaceful southern countryside retreat famed for Roman ruins, quiet vineyard estates, and hilltop stone villages.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'June to August (Lavender Season)',
    averageTemp: '27°C',
    idealDays: 4,
    vibes: ['Peace & Zen', 'Lush Nature', 'Culinary & Wine'],
    highlights: ['Senanque Abbey Lavender Fields', 'Gordes Hilltop Village', 'Châteauneuf-du-Pape Vineyards'],
    foodTypes: ['Ratatouille', 'Truffle Omelettes', 'Provençal Rosé Wine'],
    matchScore: 96,
    matchReason: 'Serene countryside tranquility among historic lavender slopes and gourmet vineyards.',
  },
  {
    id: 'dest_custom_chamonix',
    name: 'Chamonix & Mont Blanc',
    country: 'France',
    continent: 'Europe',
    tagline: 'Sky-scraping alpine glaciers & European mountaineering',
    description: 'Nestled beneath Western Europe’s highest peak, a world-famous alpine wonderland for glacier hikes and mountain cable cars.',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'December to April & July to Sept',
    averageTemp: '14°C',
    idealDays: 4,
    vibes: ['Mountains & Alpine', 'High Adventure', 'Scenic'],
    highlights: ['Aiguille du Midi Skywalk', 'Mer de Glace Ice Cave', 'Mont Blanc Cable Car'],
    foodTypes: ['Alpine Cheese Fondue', 'Savoyard Tartiflette', 'Cured Mountain Ham'],
    matchScore: 95,
    matchReason: 'Thrilling high-mountain vistas and majestic glacier trails in the French Alps.',
  },
  {
    id: 'dest_custom_mont_saint_michel',
    name: 'Mont Saint-Michel & Normandy',
    country: 'France',
    continent: 'Europe',
    tagline: 'Medieval tidal abbey surrounded by dramatic ocean tides',
    description: 'A gravity-defying Gothic monastery rising from the Atlantic shallows, famed for sweeping coastal tides and cobblestone ramparts.',
    coverImage: 'https://images.unsplash.com/photo-1546708973-b339540b5162?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to September',
    averageTemp: '20°C',
    idealDays: 3,
    vibes: ['Historic Old Towns', 'Scenic', 'Culture'],
    highlights: ['Abbey of Mont Saint-Michel', 'Tidal Bay Walking Tour', 'Rampart Panoramic Lookouts'],
    foodTypes: ['Mère Poulard Fluffy Omelette', 'Normandy Apple Tart', 'Salt Marsh Lamb'],
    matchScore: 94,
    matchReason: 'One of the world’s most magical historic architectural wonders on the Atlantic coast.',
  },
  {
    id: 'dest_custom_bordeaux',
    name: 'Bordeaux & Saint-Émilion',
    country: 'France',
    continent: 'Europe',
    tagline: 'World-renowned grand cru châteaux & 18th-century stone quays',
    description: 'A UNESCO-listed city of grand neo-classical facades, renowned as the undisputed global capital of fine wine.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to October',
    averageTemp: '22°C',
    idealDays: 3,
    vibes: ['Culinary', 'Historic Old Towns', 'Luxury Escapes'],
    highlights: ['Place de la Bourse Water Mirror', 'Saint-Émilion Underground Monolithic Church', 'Cité du Vin'],
    foodTypes: ['Canelés de Bordeaux', 'Bordeaux Grand Cru Wine', 'Entrecôte à la Bordelaise'],
    matchScore: 93,
    matchReason: 'Refined heritage architecture and world-class wine estate tastings.',
  },
  {
    id: 'dest_custom_lyon',
    name: 'Lyon & Vieux Lyon',
    country: 'France',
    continent: 'Europe',
    tagline: 'Gastronomy capital & hidden Renaissance traboules passages',
    description: 'Set along the Rhône and Saône rivers, boasting centuries of culinary prestige, Roman amphitheatres, and Renaissance lanes.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to October',
    averageTemp: '22°C',
    idealDays: 3,
    vibes: ['Culinary', 'Historic Old Towns', 'Culture'],
    highlights: ['Fourvière Basilica Overlook', 'Vieux Lyon Secret Traboules', 'Les Halles de Lyon Paul Bocuse'],
    foodTypes: ['Traditional Bouchon Quenelle', 'Brioche aux Pralines', 'Artisanal Charcuterie'],
    matchScore: 92,
    matchReason: 'Legendary French culinary excellence combined with ancient Renaissance heritage.',
  },
  {
    id: 'dest_custom_annecy',
    name: 'Annecy & Lake Annecy',
    country: 'France',
    continent: 'Europe',
    tagline: 'Crystal-clear alpine lake waters & pastel canal quarters',
    description: 'Nicknamed the Venice of the Alps, featuring flower-lined canals, fairy-tale island castles, and emerald alpine waters.',
    coverImage: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'June to September',
    averageTemp: '24°C',
    idealDays: 3,
    vibes: ['Chill & Coastal', 'Mountains & Alpine', 'Romantic'],
    highlights: ['Palais de l’Île Old Prison', 'Lake Annecy Kayaking & Boating', 'Pont des Amours'],
    foodTypes: ['Fresh Lake Trout', 'Raclette', 'Alpine Bilberry Tarts'],
    matchScore: 91,
    matchReason: 'Idyllic fairy-tale lake serenity framed by dramatic French alpine peaks.',
  },
];

/**
 * Curated destinations for Japan (Kyoto, Tokyo, Osaka, Mount Fuji)
 */
const JAPAN_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_kyoto',
    name: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    tagline: 'Ancient Zen gardens & timeless bamboo groves',
    description: 'Immerse yourself in tranquil temple sanctuaries, centuries-old tea rituals, and ethereal bamboo paths.',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'March to May & Oct to Nov',
    averageTemp: '18°C',
    idealDays: 5,
    vibes: ['Peace & Zen', 'Culture', 'Historic Old Towns'],
    highlights: ['Arashiyama Bamboo Grove', 'Fushimi Inari Taisha', 'Gion Historic District'],
    foodTypes: ['Kaiseki Multi-course', 'Matcha Tea', 'Artisanal Ramen'],
    matchScore: 98,
    matchReason: 'Profound peaceful rhythm with timeless Japanese temple architecture.',
  },
  {
    id: 'dest_custom_tokyo',
    name: 'Tokyo (Shinjuku & Shibuya)',
    country: 'Japan',
    continent: 'Asia',
    tagline: 'Neon skylines, ancient shrines & Michelin culinary masters',
    description: 'The world’s most dynamic metropolis, blending cutting-edge futuristic districts with serene centuries-old Meiji forests.',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'March to May & Sept to Nov',
    averageTemp: '19°C',
    idealDays: 5,
    vibes: ['Metropolis', 'Culinary', 'Culture'],
    highlights: ['Shibuya Crossing at Night', 'Senso-ji Temple Asakusa', 'TeamLab Planets Digital Art'],
    foodTypes: ['Toyosu Market Sushi', 'Tsukemen Ramen', 'Yakitori in Memory Lane'],
    matchScore: 97,
    matchReason: 'Electrifying city energy combined with hidden culinary gems and ancient shrines.',
  },
  {
    id: 'dest_custom_fuji',
    name: 'Mount Fuji & Lake Kawaguchi',
    country: 'Japan',
    continent: 'Asia',
    tagline: 'Snow-capped sacred volcano reflected in tranquil lakes',
    description: 'The iconic symbol of Japan, surrounded by hot spring onsens, pine-fringed lakes, and pagodas with mountain panoramas.',
    coverImage: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to June & Oct to Nov',
    averageTemp: '15°C',
    idealDays: 3,
    vibes: ['Mountains & Alpine', 'Peace & Zen', 'Scenic'],
    highlights: ['Chureito Pagoda Viewpoint', 'Lake Kawaguchiko Onsens', 'Fuji Five Lakes Drive'],
    foodTypes: ['Hoto Noodle Stew', 'Koshu Wine', 'Fresh Mountain Trout'],
    matchScore: 96,
    matchReason: 'Breathtaking mountain serenity with iconic sacred volcano views.',
  },
  {
    id: 'dest_custom_osaka',
    name: 'Osaka & Dotonbori',
    country: 'Japan',
    continent: 'Asia',
    tagline: 'Japan’s street food capital & lively neon canal walkways',
    description: 'A vibrant, warm-hearted culinary hub famous for sizzling street food, grand feudal castle towers, and lively entertainment.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'March to May & Oct to Nov',
    averageTemp: '20°C',
    idealDays: 4,
    vibes: ['Street Food', 'Metropolis', 'Historic'],
    highlights: ['Dotonbori Glico Sign Walk', 'Osaka Castle Grounds', 'Shinsekai Retro Alleyways'],
    foodTypes: ['Crispy Takoyaki', 'Okonomiyaki Pancakes', 'Kushikatsu Skewers'],
    matchScore: 95,
    matchReason: 'World-renowned street gastronomy and infectious city hospitality.',
  },
  {
    id: 'dest_custom_nara',
    name: 'Nara Ancient Capital',
    country: 'Japan',
    continent: 'Asia',
    tagline: 'Gentle sacred deer & colossal Great Bronze Buddha',
    description: 'Japan’s first permanent imperial capital, where hundreds of free-roaming deer wander among ancient wooden temples.',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to June & Oct to Nov',
    averageTemp: '18°C',
    idealDays: 2,
    vibes: ['Peace & Zen', 'Historic Old Towns', 'Lush Nature'],
    highlights: ['Todai-ji Great Buddha', 'Nara Deer Park', 'Kasuga Taisha Lantern Shrine'],
    foodTypes: ['Kakinoha-zushi (Persimmon Leaf Sushi)', 'Miwa Somen', 'Fresh Mochi'],
    matchScore: 94,
    matchReason: 'Harmonious historic temples surrounded by ancient sacred woodlands.',
  },
  {
    id: 'dest_custom_sapporo',
    name: 'Sapporo & Hokkaido Wilderness',
    country: 'Japan',
    continent: 'Asia',
    tagline: 'Powder snow slopes, thermal onsens & fresh crab feasts',
    description: 'Japan’s northern wild frontier, renowned for legendary powder skiing, lavender farms in summer, and world-class seafood.',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'December to March (Snow) & July (Flowers)',
    averageTemp: '12°C',
    idealDays: 5,
    vibes: ['Mountains & Alpine', 'High Adventure', 'Culinary'],
    highlights: ['Niseko Powder Snow Trails', 'Otaru Canal Historic Walk', 'Jozankei Hot Springs'],
    foodTypes: ['Hokkaido King Crab', 'Miso Butter Corn Ramen', 'Genghis Khan Grilled Lamb'],
    matchScore: 93,
    matchReason: 'Pristine northern alpine mountains and extraordinary seasonal dining.',
  },
];

/**
 * Curated destinations for Italy (Rome, Amalfi, Florence, Venice)
 */
const ITALY_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_rome',
    name: 'Rome',
    country: 'Italy',
    continent: 'Europe',
    tagline: 'Ancient imperial ruins, Baroque piazzas & open-air history',
    description: 'The Eternal City where classical antiquity meets vibrant street life, historic cobblestones, and world-class trattorias.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to June & Sept to Oct',
    averageTemp: '22°C',
    idealDays: 4,
    vibes: ['Historic Old Towns', 'Vibrant & Cultural', 'Architecture'],
    highlights: ['The Colosseum', 'Pantheon & Trevi Fountain', 'Vatican Museums'],
    foodTypes: ['Cacio e Pepe', 'Roman Pizza al Taglio', 'Artisan Tiramisù'],
    matchScore: 98,
    matchReason: 'Millennia of world-heritage architecture, iconic monuments, and culinary masters.',
  },
  {
    id: 'dest_custom_amalfi',
    name: 'Amalfi Coast (Positano & Ravello)',
    country: 'Italy',
    continent: 'Europe',
    tagline: 'Pastel cliffside villages over sapphire Mediterranean seas',
    description: 'Spectacular seaside roads, terraced lemon orchards, and coastal glamour etched into dramatic limestone cliffs.',
    coverImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to October',
    averageTemp: '24°C',
    idealDays: 4,
    vibes: ['Chill & Coastal', 'Romantic', 'Scenic'],
    highlights: ['Positano Cliffside', 'Path of the Gods', 'Ravello Gardens'],
    foodTypes: ['Fresh Seafood Pasta', 'Limoncello', 'Artisan Gelato'],
    matchScore: 97,
    matchReason: 'Offers breathtaking coastal elegance with sublime Mediterranean dining.',
  },
  {
    id: 'dest_custom_florence',
    name: 'Florence & Tuscan Hills',
    country: 'Italy',
    continent: 'Europe',
    tagline: 'Renaissance masterpieces & sun-drenched Chianti vineyards',
    description: 'The cradle of the Renaissance, filled with world-famous galleries, terracotta duomos, and cypress-lined countryside lanes.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to October',
    averageTemp: '23°C',
    idealDays: 4,
    vibes: ['Historic Old Towns', 'Culinary & Wine', 'Architecture'],
    highlights: ['Duomo di Firenze & Giotto Campanile', 'Uffizi Gallery', 'Ponte Vecchio Sunset'],
    foodTypes: ['Bistecca alla Fiorentina', 'Chianti Classico Wine', 'Ribollita Tuscan Stew'],
    matchScore: 96,
    matchReason: 'Unrivaled artistic heritage paired with idyllic rolling vineyard landscapes.',
  },
  {
    id: 'dest_custom_venice',
    name: 'Venice & Venetian Lagoon',
    country: 'Italy',
    continent: 'Europe',
    tagline: 'Floating marble palaces & romantic gondola canals',
    description: 'A miraculous city built on water, featuring Gothic bridges, shimmering lagoons, and labyrinthine pedestrian alleyways.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to June & Sept to Nov',
    averageTemp: '21°C',
    idealDays: 3,
    vibes: ['Romantic', 'Historic Old Towns', 'Scenic'],
    highlights: ['St. Mark’s Basilica & Piazza', 'Grand Canal Gondola Ride', 'Rialto Bridge Walk'],
    foodTypes: ['Cicchetti & Spritz', 'Squid Ink Risotto', 'Fresh Bellini Cocktail'],
    matchScore: 95,
    matchReason: 'Timeless floating romance and one of the world’s most unique architectural achievements.',
  },
  {
    id: 'dest_custom_dolomites',
    name: 'The Dolomites & Val Gardena',
    country: 'Italy',
    continent: 'Europe',
    tagline: 'Jagged limestone peaks & alpine meadow wonderlands',
    description: 'A UNESCO World Heritage mountain range famous for dramatic pale pinnacles, turquoise glacial lakes, and alpine chalets.',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'June to September & Dec to March',
    averageTemp: '16°C',
    idealDays: 5,
    vibes: ['Mountains & Alpine', 'High Adventure', 'Scenic'],
    highlights: ['Tre Cime di Lavaredo Circuit', 'Lago di Braies Boat Ride', 'Seceda Ridgeline Panorama'],
    foodTypes: ['Speck Ham & Knödel Dumplings', 'Apple Strudel', 'South Tyrol Pinot Grigio'],
    matchScore: 94,
    matchReason: 'Breathtaking dramatic alpine geology and crisp mountain hiking trails.',
  },
];

/**
 * Curated destinations for Switzerland (Zermatt, Interlaken, Lucerne)
 */
const SWISS_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_zermatt',
    name: 'Zermatt & Matterhorn',
    country: 'Switzerland',
    continent: 'Europe',
    tagline: 'Matterhorn views, glacier trails & alpine luxury',
    description: 'A car-free alpine village nestled at the foot of the Matterhorn, offering pure mountain air and world-class scenery.',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'December to April & July to Oct',
    averageTemp: '12°C',
    idealDays: 5,
    vibes: ['Mountains & Alpine', 'Luxury Escapes', 'Peace & Zen'],
    highlights: ['Gornergrat Railway', 'Matterhorn Glacier Paradise', 'Five Lakes Walk'],
    foodTypes: ['Cheese Fondue', 'Raclette', 'Swiss Chocolate'],
    matchScore: 98,
    matchReason: 'The world benchmark for dramatic alpine beauty and serene mountain retreats.',
  },
  {
    id: 'dest_custom_interlaken',
    name: 'Interlaken & Jungfrau Region',
    country: 'Switzerland',
    continent: 'Europe',
    tagline: 'Top of Europe glacier trains & twin turquoise lakes',
    description: 'Nestled between Lake Thun and Lake Brienz, serving as the adventure gateway to the snow-capped Eiger and Jungfrau summits.',
    coverImage: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to October',
    averageTemp: '18°C',
    idealDays: 4,
    vibes: ['Mountains & Alpine', 'High Adventure', 'Scenic'],
    highlights: ['Jungfraujoch Sphinx Observatory', 'Harder Kulm Viewpoint', 'Lake Brienz Steamboat'],
    foodTypes: ['Rösti with Fried Egg', 'Alpine Fondue', 'Swiss Meringue'],
    matchScore: 97,
    matchReason: 'High-altitude glacier rail journeys and world-renowned alpine adventure.',
  },
  {
    id: 'dest_custom_lauterbrunnen',
    name: 'Lauterbrunnen & Mürren',
    country: 'Switzerland',
    continent: 'Europe',
    tagline: 'Valley of 72 waterfalls & cliffside wooden chalets',
    description: 'An ethereal deep alpine trough where sheer rock faces plunge beside roaring waterfalls and quiet wildflower meadows.',
    coverImage: 'https://images.unsplash.com/photo-1546708973-b339540b5162?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'June to September',
    averageTemp: '19°C',
    idealDays: 3,
    vibes: ['Lush Nature', 'Peace & Zen', 'Scenic'],
    highlights: ['Staubbach Falls', 'Trümmelbach Underground Glacial Falls', 'Mürren Car-Free Village'],
    foodTypes: ['Fresh Alpine Milk & Cheese', 'Warm Fruit Tarts', 'Berner Platte'],
    matchScore: 96,
    matchReason: 'Fairy-tale valley serenity with dramatic vertical waterfalls and peaceful trails.',
  },
  {
    id: 'dest_custom_lucerne',
    name: 'Lucerne & Mount Pilatus',
    country: 'Switzerland',
    continent: 'Europe',
    tagline: 'Historic covered bridges & scenic lake paddle steamers',
    description: 'A charming medieval lakeside jewel framed by Mount Pilatus and Mount Rigi, featuring 14th-century wooden bridges.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to October',
    averageTemp: '20°C',
    idealDays: 3,
    vibes: ['Historic Old Towns', 'Scenic', 'Relaxed'],
    highlights: ['Kapellbrücke (Chapel Bridge)', 'Pilatus Golden Round Trip Cogwheel', 'Lake Lucerne Cruise'],
    foodTypes: ['Luzerner Chügelipastete', 'Swiss Pralines', 'Fresh Lake Fish'],
    matchScore: 95,
    matchReason: 'Quintessential Swiss lake elegance paired with easy mountain rail summits.',
  },
];

/**
 * Curated destinations for Goa
 */
const GOA_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_goa_south',
    name: 'South Goa (Palolem & Agonda)',
    country: 'India',
    continent: 'Asia',
    state: 'Goa',
    tagline: 'Crescent palm shores, tranquil coves & fresh sea breezes',
    description: 'An unhurried coastal sanctuary of crescent sands, dolphin boat safaris, rustic beach huts, and fresh seafood thalis.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'November to March',
    averageTemp: '29°C',
    idealDays: 4,
    vibes: ['Chill & Coastal', 'Beaches', 'Peace & Zen'],
    highlights: ['Palolem Crescent Beach', 'Cabo de Rama Fort Ramparts', 'Butterfly Beach Boat Excursion'],
    foodTypes: ['Goan Fish Curry Thali', 'Prawn Balchão', 'Bebinca Coconut Dessert'],
    matchScore: 98,
    matchReason: 'The benchmark for relaxing beachside rhythm and authentic coastal dining.',
  },
  {
    id: 'dest_custom_goa_north',
    name: 'North Goa (Vagator & Ashwem)',
    country: 'India',
    continent: 'Asia',
    state: 'Goa',
    tagline: 'Red laterite cliff sunsets, chic shacks & coastal flea markets',
    description: 'A vibrant shoreline boasting dramatic Portuguese fortress lookouts, bohemian boutiques, and vibrant sunset cafes.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'October to April',
    averageTemp: '29°C',
    idealDays: 4,
    vibes: ['Chill & Coastal', 'Artisan Cafes', 'Vibrant & Cultural'],
    highlights: ['Chapora Fort Sunset', 'Ashwem Clean White Sands', 'Anjuna Flea Market'],
    foodTypes: ['Fresh Tandoori Snapper', 'Goan Pork Vindaloo', 'Feni & Kokum Coolers'],
    matchScore: 97,
    matchReason: 'Vibrant coastal lifestyle paired with dramatic cliff views and beach clubs.',
  },
  {
    id: 'dest_custom_goa_panaji',
    name: 'Panaji & Fontainhas Latin Quarter',
    country: 'India',
    continent: 'Asia',
    state: 'Goa',
    tagline: 'Mustard Portuguese villas & cobbled heritage avenues',
    description: 'Asia’s only Latin Quarter, adorned with pastel heritage mansions, wrought-iron balconies, and tranquil Mandovi river cruises.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'October to March',
    averageTemp: '28°C',
    idealDays: 2,
    vibes: ['Historic Old Towns', 'Culture', 'Architecture'],
    highlights: ['Fontainhas Heritage Walking Tour', 'Immaculate Conception Church', 'Mandovi River Sunset Cruise'],
    foodTypes: ['Goan Poee Bread', 'Chicken Xacuti', 'Local Bakery Sweets'],
    matchScore: 96,
    matchReason: 'Historic Indo-Portuguese architecture and quaint artistic cafes.',
  },
  {
    id: 'dest_custom_goa_dudhsagar',
    name: 'Dudhsagar Falls & Mollem Wildlife',
    country: 'India',
    continent: 'Asia',
    state: 'Goa',
    tagline: 'Four-tiered milky mountain cascades in dense rainforests',
    description: 'One of India’s tallest and most dramatic waterfalls, roaring through the Western Ghats jungle canopy with natural swimming pools.',
    coverImage: 'https://images.unsplash.com/photo-1546708973-b339540b5162?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'October to February',
    averageTemp: '25°C',
    idealDays: 2,
    vibes: ['Lush Nature', 'High Adventure', 'Scenic'],
    highlights: ['Dudhsagar Waterfall Jeep Safari', 'Bhagwan Mahaveer Sanctuary', 'Natural Pool Swimming'],
    foodTypes: ['Goan Village Thali', 'Fresh Coconut Water', 'Spiced Country Chicken'],
    matchScore: 95,
    matchReason: 'Spectacular jungle rainforest cascades away from the coastal crowds.',
  },
];

/**
 * Curated destinations for Dubai / UAE
 */
const DUBAI_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_dubai_marina',
    name: 'Dubai Marina & Palm Jumeirah',
    country: 'United Arab Emirates',
    continent: 'Asia',
    tagline: 'Iconic man-made archipelago & sky-scraping yacht harbors',
    description: 'The pinnacle of luxury coastal living, boasting world-famous palm islands, private beach clubs, and soaring architectural towers.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'November to April',
    averageTemp: '25°C',
    idealDays: 4,
    vibes: ['Luxury Escapes', 'Chill & Coastal', 'Metropolis'],
    highlights: ['The View at The Palm', 'Dubai Marina Yacht Cruise', 'JBR Beach Walk'],
    foodTypes: ['Fresh Mediterranean Seafood', 'Emirati Machboos', 'Artisan Arabic Sweets'],
    matchScore: 98,
    matchReason: 'Pristine luxury waterfront lifestyle and iconic modern architectural marvels.',
  },
  {
    id: 'dest_custom_dubai_downtown',
    name: 'Downtown Dubai & Burj Khalifa',
    country: 'United Arab Emirates',
    continent: 'Asia',
    tagline: 'World’s tallest spire & mesmerizing fountain choreography',
    description: 'The energetic heartbeat of the Emirates, where the 828m Burj Khalifa towers over illuminated musical fountains and luxury malls.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'November to March',
    averageTemp: '24°C',
    idealDays: 3,
    vibes: ['Metropolis', 'Architecture', 'Shopping'],
    highlights: ['Burj Khalifa Level 148 Sky Deck', 'Dubai Fountain Evening Show', 'Dubai Opera & Boulevard'],
    foodTypes: ['Fine Dining Rooftop Cuisine', 'Authentic Shawarma', 'Kunafa with Pistachio'],
    matchScore: 97,
    matchReason: 'Record-breaking urban architecture and world-class luxury entertainment.',
  },
  {
    id: 'dest_custom_dubai_desert',
    name: 'Dubai Desert Conservation Reserve',
    country: 'United Arab Emirates',
    continent: 'Asia',
    tagline: 'Golden rolling dunes, Arabian oryx & starlit Bedouin camps',
    description: 'A tranquil desert sanctuary where sweeping red sand dunes meet luxury eco-lodges, falconry, and majestic sunset camel treks.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'October to April',
    averageTemp: '22°C',
    idealDays: 2,
    vibes: ['Peace & Zen', 'High Adventure', 'Scenic'],
    highlights: ['Sunset Dune Bashing & Sandboarding', 'Arabian Wildlife Safari', 'Starlight Bedouin Dinner'],
    foodTypes: ['Charcoal Grilled Kebabs', 'Traditional Hummus & Mezze', 'Arabic Spiced Coffee with Dates'],
    matchScore: 96,
    matchReason: 'Peaceful desert stillness and authentic Arabian desert culture.',
  },
];

/**
 * Curated destinations for Maldives
 */
const MALDIVES_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_maldives_baa',
    name: 'Baa Atoll & Hanifaru Bay',
    country: 'Maldives',
    continent: 'Asia',
    tagline: 'UNESCO marine biosphere & majestic manta ray feeding aggregations',
    description: 'A protected marine reserve world-famous for swimming with hundreds of graceful manta rays and whale sharks over vibrant corals.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to November (Manta Season) & Dec to April',
    averageTemp: '29°C',
    idealDays: 5,
    vibes: ['Chill & Coastal', 'Marine Wildlife', 'Luxury Escapes'],
    highlights: ['Hanifaru Bay Manta Snorkel', 'Overwater Bungalow Sunrise', 'House Reef Coral Safari'],
    foodTypes: ['Fresh Maldivian Yellowfin Tuna', 'Mas Huni with Roshi', 'Tropical Coconut Sorbet'],
    matchScore: 98,
    matchReason: 'Unmatched crystalline waters, overwater bungalow peace, and breathtaking marine wildlife.',
  },
  {
    id: 'dest_custom_maldives_maafushi',
    name: 'Maafushi & South Malé Atoll',
    country: 'Maldives',
    continent: 'Asia',
    tagline: 'Turquoise island lagoons & accessible tropical reef diving',
    description: 'An idyllic local island ringed with powdery white sands, vibrant beach cafes, water sports, and shallow stingray lagoons.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'December to April',
    averageTemp: '29°C',
    idealDays: 4,
    vibes: ['Beaches', 'Water Sports', 'Relaxed'],
    highlights: ['Sandbank Island Picnic', 'Nurse Shark & Turtle Snorkel', 'Bikini Beach Sunset'],
    foodTypes: ['Grilled Reef Fish', 'Coconut Curry Meals', 'Fresh Watermelon Juice'],
    matchScore: 96,
    matchReason: 'Postcard-perfect tropical waters with easy lagoon access and island activities.',
  },
];

/**
 * Curated destinations for Greece / Santorini
 */
const GREECE_DESTINATIONS: Destination[] = [
  {
    id: 'dest_custom_santorini',
    name: 'Santorini (Oia & Fira)',
    country: 'Greece',
    continent: 'Europe',
    tagline: 'Whitewashed Aegean villages perched over volcanic calderas',
    description: 'Iconic cobalt-blue domes, dramatic volcanic cliffs, and legendary golden sunsets overlooking the Aegean Sea.',
    coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'May to October',
    averageTemp: '25°C',
    idealDays: 4,
    vibes: ['Romantic', 'Chill & Coastal', 'Scenic'],
    highlights: ['Oia Sunset Castle', 'Red Beach', 'Caldera Boat Tour'],
    foodTypes: ['Greek Salad with Feta', 'Grilled Calamari', 'Assyrtiko Wine'],
    matchScore: 98,
    matchReason: 'Postcard-perfect Greek island romance with sublime seaside dining.',
  },
  {
    id: 'dest_custom_mykonos',
    name: 'Mykonos & Little Venice',
    country: 'Greece',
    continent: 'Europe',
    tagline: 'Chic whitewashed windmills, cobblestone lanes & azure coves',
    description: 'A dazzling Cycladic gem celebrated for vibrant seaside nightlife, historic windmills, and pristine sandy beaches.',
    coverImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'June to September',
    averageTemp: '27°C',
    idealDays: 4,
    vibes: ['Chill & Coastal', 'Luxury Escapes', 'Beaches'],
    highlights: ['Mykonos Windmills', 'Little Venice Waterfront Drinks', 'Psarou Beach Club'],
    foodTypes: ['Souvlaki with Tzatziki', 'Grilled Octopus', 'Greek Baklava'],
    matchScore: 96,
    matchReason: 'World-renowned island glamour, azure coves, and lively seaside dining.',
  },
  {
    id: 'dest_custom_athens',
    name: 'Athens & The Acropolis',
    country: 'Greece',
    continent: 'Europe',
    tagline: 'Cradle of Western civilization & vibrant Plaka tavernas',
    description: 'Where the 2,500-year-old Parthenon crowns the hill above buzzing modern neighborhood cafes, rooftop bars, and ancient agoras.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop',
    gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
    bestSeason: 'April to June & Sept to Nov',
    averageTemp: '22°C',
    idealDays: 3,
    vibes: ['Historic Old Towns', 'Culture', 'Architecture'],
    highlights: ['Acropolis & Parthenon', 'Plaka Cobbled Quarter', 'Temple of Olympian Zeus'],
    foodTypes: ['Traditional Moussaka', 'Spanakopita', 'Greek Frappé Coffee'],
    matchScore: 95,
    matchReason: 'Ancient classical monuments paired with lively Mediterranean rooftop tavernas.',
  },
];

/**
 * Dynamic destination synthesizer for any arbitrary custom destination entered by user
 */
function synthesizeCustomDestinations(
  targetTitle: string,
  params: AIDestinationSearchParams
): Destination[] {
  const images = UNSPLASH_IMAGES;
  const sanitized = targetTitle.replace(/[^a-zA-Z0-9\s]/g, '').trim() || 'Curated Escape';

  return [
    {
      id: `dest_custom_${sanitized.toLowerCase().replace(/\s+/g, '_')}_center`,
      name: `${sanitized} City Center & Historic Heart`,
      country: sanitized,
      continent: 'Global',
      tagline: `Historic monuments, artisanal quarters & vibrant local life in ${sanitized}`,
      description: `Experience the authentic pulse of ${sanitized}. Wander through storied cobblestone lanes, iconic viewpoints, and captivating neighborhood heritage.`,
      coverImage: images.historic[0],
      gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
      bestSeason: 'Spring & Autumn (April to October)',
      averageTemp: '22°C',
      idealDays: 4,
      vibes: ['Historic Old Towns', 'Culture', 'Artisan Cafes'],
      highlights: [`${sanitized} Old Town Promenade`, `${sanitized} Historic Cathedral / Citadel`, 'Artisan Market & City Square'],
      foodTypes: ['Authentic Regional Delicacies', 'Locally Crafted Wines & Bakes', 'Market Street Food'],
      matchScore: 98,
      matchReason: `Custom curated specifically for your exploration in ${sanitized}, matching your travel preferences.`,
    },
    {
      id: `dest_custom_${sanitized.toLowerCase().replace(/\s+/g, '_')}_coast`,
      name: `${sanitized} Coastal Bay & Scenic Waters`,
      country: sanitized,
      continent: 'Global',
      tagline: `Azure waters, gentle coastal breezes & seaside sunset dining in ${sanitized}`,
      description: `Unwind along the panoramic waterfront of ${sanitized}. Golden sunlight reflects across tranquil coastal bays lined with seaside promenades.`,
      coverImage: images.coastal[1],
      gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
      bestSeason: 'May to September',
      averageTemp: '26°C',
      idealDays: 3,
      vibes: ['Chill & Coastal', 'Scenic Views', 'Relaxed'],
      highlights: [`${sanitized} Sunset Waterfront Pier`, 'Coastal Boat Excursion', 'Beachside Promenade Walk'],
      foodTypes: ['Fresh Catch Seafood', 'Coastal Fruit Cocktails', 'Local Seaside Grills'],
      matchScore: 97,
      matchReason: `Delivers refreshing coastal relaxation tailored to your desired travel pace.`,
    },
    {
      id: `dest_custom_${sanitized.toLowerCase().replace(/\s+/g, '_')}_peaks`,
      name: `${sanitized} Panoramic Ridge & Mountain Trails`,
      country: sanitized,
      continent: 'Global',
      tagline: `High-altitude lookouts, crisp mountain air & alpine serenity in ${sanitized}`,
      description: `Ascend to the breathtaking highlands surrounding ${sanitized}, where cool breezes and panoramic valley vistas create unforgettable mornings.`,
      coverImage: images.mountain[0],
      gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
      bestSeason: 'June to October',
      averageTemp: '17°C',
      idealDays: 3,
      vibes: ['Mountains & Alpine', 'Lush Nature', 'Peace & Zen'],
      highlights: [`${sanitized} Summit Viewpoint`, 'Panoramic Ridge Trail', 'Mountain Pine Forest Walk'],
      foodTypes: ['Hearty Highland Stew', 'Warm Spiced Mountain Brews', 'Estate Cheeses'],
      matchScore: 96,
      matchReason: `Crisp high-altitude perspectives and tranquil nature immersion.`,
    },
    {
      id: `dest_custom_${sanitized.toLowerCase().replace(/\s+/g, '_')}_nature`,
      name: `${sanitized} Sanctuary & Eco Reserve`,
      country: sanitized,
      continent: 'Global',
      tagline: `Lush green sanctuaries, peaceful waters & undisturbed nature in ${sanitized}`,
      description: `A haven of natural biodiversity and quiet trails where native flora and scenic rivers offer peace away from busy routes.`,
      coverImage: images.nature[0],
      gradient: 'from-[#5B0B24] via-[#C2185B] to-[#FF7A3D]',
      bestSeason: 'October to May',
      averageTemp: '23°C',
      idealDays: 3,
      vibes: ['Lush Nature', 'Peace & Zen', 'Wildlife Safari'],
      highlights: [`${sanitized} Botanical Eco Trail`, 'Scenic River Boat Safari', 'Secret Forest Waterfall'],
      foodTypes: ['Farm-to-Table Organic Meals', 'Fresh Orchard Juices', 'Local Herbal Infusions'],
      matchScore: 95,
      matchReason: `Untouched nature and relaxing green open spaces strictly in ${sanitized}.`,
    },
  ];
}

/**
 * Master Resolver for Custom Locations in Astra 6 Search
 */
export function resolveCustomLocationSearch(
  target: string,
  params: AIDestinationSearchParams
): AIDestinationSearchResponse {
  const clean = target.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').trim();
  const limit = params.limit || 8;

  let pool: Destination[];
  let regionLabel: string;

  if (clean.includes('paris') || clean.includes('france') || clean.includes('french')) {
    pool = FRANCE_DESTINATIONS;
    regionLabel = 'Paris & France';
  } else if (clean.includes('japan') || clean.includes('kyoto') || clean.includes('tokyo') || clean.includes('osaka') || clean.includes('fuji')) {
    pool = JAPAN_DESTINATIONS;
    regionLabel = 'Japan';
  } else if (clean.includes('italy') || clean.includes('rome') || clean.includes('amalfi') || clean.includes('florence') || clean.includes('venice') || clean.includes('tuscany')) {
    pool = ITALY_DESTINATIONS;
    regionLabel = 'Italy';
  } else if (clean.includes('switzerland') || clean.includes('swiss') || clean.includes('alps') || clean.includes('zermatt') || clean.includes('interlaken')) {
    pool = SWISS_DESTINATIONS;
    regionLabel = 'Switzerland';
  } else if (clean.includes('goa')) {
    pool = GOA_DESTINATIONS;
    regionLabel = 'Goa';
  } else if (clean.includes('dubai') || clean.includes('uae') || clean.includes('emirates') || clean.includes('abu dhabi')) {
    pool = DUBAI_DESTINATIONS;
    regionLabel = 'Dubai & UAE';
  } else if (clean.includes('maldives') || clean.includes('male atoll')) {
    pool = MALDIVES_DESTINATIONS;
    regionLabel = 'Maldives';
  } else if (clean.includes('greece') || clean.includes('santorini') || clean.includes('athens') || clean.includes('mykonos')) {
    pool = GREECE_DESTINATIONS;
    regionLabel = 'Greece & Santorini';
  } else {
    // Dynamic synthesizer for ANY custom location (Fiji, Norway, Egypt, Vienna, etc.)
    const title = formatTitleCase(target);
    pool = synthesizeCustomDestinations(title, params);
    regionLabel = title;
  }

  const ranked = filterAndRankCuratedDestinations(pool, params);

  return {
    query: target || regionLabel,
    summary: generateSearchSummary(ranked, params, regionLabel),
    destinations: ranked.slice(0, limit),
    suggestedFollowUps: generateFollowUps(ranked, params),
    source: 'smart_taste_fallback',
  };
}
